### ISSUE TITLE
Instantiation Syntax Suggestions

### ISSUE THREAD

**Issue by mjhasbach** [gettyimages/gettyimages-api_nodejs#10]
I have a minor suggestion regarding the module instantiation syntax. Here is an example of requiring credentials from another file and passing them to the constructor:
```
var credentials = require('./gettyConfig'),
    getty = new require('connectsdk')(credentials.apiKey, credentials.apiSecret);
```
That could be more tersely achieved with [Function.prototype.apply()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply) if `ConnectSdk` was a regular function instead of a constructor function. It is possible to use the [spread operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator), but that is currently only supported in Node if the `--es-staging` flag is supplied. For example:
```
var getty = new require('connectsdk')(...require('./server/gettyConfig'));
```
Another possibility is the constructor accepting an object argument with `apiKey`, `apiSecret`, etc. properties.

**Comment by mapitman** [comment]
Something to keep in mind with the SDK is that it handles multiple OAuth2 grant types which are supported by our API:
+ Resource Owner, which requires API key, API secret, username, and user password
+ Refresh Token (not supported by the NodeJS SDK yet), which requires API key, API secret and a refresh token (received when calling Resource Owner grant.)
+ Client Credentials, which requires API key and API secret

Our API also supports calling certain operations semi-anonymously using only an API key.  

We tried to abstract some of that away with the SDK as we have had quite a few developers who have a difficult time grasping some of the concepts around OAuth2 and token management.

API key and secret authorize an application to use our API. Username and password authorize that application to access resources for that particular user.

**Comment by mjhasbach** [comment]
@mapitman thanks for the reply. I should have learned more about Getty authentication before opening this ticket. I updated the issue title and description to include only the instantiation syntax suggestion.

**Comment by mapitman** [comment]
OK, we will take your suggestion into consideration the next time we are making updates.
