### ISSUE TITLE
download an image example throws an error

### ISSUE THREAD

**Issue by przemyslawpluta** [gettyimages/gettyimages-api_nodejs#13]
Image download example provided in [README.md](https://github.com/gettyimages/gettyimages-api_nodejs#download-an-image) seems be be based on an older version of an API and throws and error.

```js
var api = require("gettyimages-api");
var creds = { apiKey: "your_api_key", apiSecret: "your_api_secret", username: "your_username", password: "your_password" };
var client = new api (creds);
client.download().withId('467073457').execute(function(err, response) {
        if (err) throw err
        console.log(response.uri);
});
```

```bash
TypeError: client.download is not a function
```
Based on client abilities it looks like `downloads` should be used instead ...

```js
GettyImagesApi {
  getAccessToken: [Function],
  images: [Function],
  videos: [Function],
  search: [Function],
  collections: [Function],
  countries: [Function],
  events: [Function],
  downloads: [Function] }
```

After trying:

```js
client.downloads().images().withId('467073457').execute(function execute(err, response) {
    if (err) throw err
    console.log(response);
});
```

I'm getting:

```js
{ ErrorCode: 'NoDownloadAuthorization',
  ErrorMessage: 'No download authorization were found for asset 467073457. Perhaps the user has no active product types.' }
```

Is there a need for an access token in here somewhere? Examples aren't very specific in regards to this. Can we get examples updated. 

Thanks.

**Comment by przemyslawpluta** [comment]
OK. I've trued to replicated the videos example and that seem to work. So I guess asset `467073457 ` is not permitted for download hence the error returned from the API.

Would be good to update the examples anyway.

**Comment by mapitman** [comment]
Fixed sample code. Changed image id to something that a sandbox key will have access to.
