### ISSUE TITLE
CORS problem on local

### ISSUE THREAD

**Issue by redthree** [gettyimages/gettyimages-api_nodejs#13]
Hi, I tried to implement the library but I have this issue with he requests.

Error message:
`No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

My code:
```
import config from "../env";
var api = require("gettyimages-api");

var creds = {
  apiKey: config.GETTY_API_KEY,
  apiSecret: config.GETTY_API_SECRET,
  username: "myemail",
  password: "mypassword",
};

const gettyApi = new api(creds);

gettyApi.getAccessToken().then(
  (response) => {
    console.log(response.access_token);
  },
  (err) => {
    throw err;
  }
);
```

**Comment by mapitman** [comment]
Can you give us a little more info about how you are using the SDK? Are you trying to run this code from a web browser? If not, what version of NodeJS are you using?

**Comment by redthree** [comment]
Yes, from a browser. I'm trying to integrate it with a React application. My Node version is 10.16.3

**Comment by mapitman** [comment]
Resource Owner and Client Credentials OAuth 2.0 flows are not allowed to be called from a Web Browser. You would need to implement Authorization Code Flow as documented here: https://developer.gettyimages.com/api/oauth2.html#authorization-code-grant

The SDK doesn't help out for that flow. It also doesn't support passing in an access token to the constructor at this time. If you want to implement that, we'd love to accept a pull request :)

**Comment by mapitman** [comment]
Closing as it's been 2 weeks.
