### ISSUE TITLE
Bug with adding integers to query param

### ISSUE THREAD

**Issue by allison-zhao** [gettyimages/gettyimages-api_nodejs#15]
I was using `withPage()` and `withPageSize()` to get a paginated response but it didn't work, so I looked more into the code and found out that there is this check (https://github.com/gettyimages/gettyimages-api_nodejs/blob/master/lib/searchimageseditorial.js#L202)

```
function addParameter(params, key, value) {
    if (value && value.length > 0) {
        if (value.constructor === Array) {
            params[key] = value.join(",");
        } else {
            params[key] = value;
        }
    }
}
```

When an integer is passed in `value` instead of a string, this check fails and later fails to add this param to the query. I was also misled by the wrong examples in README (`withPage` and `withPageSize` were both called with an integer) and the initialization using integers, for example, `page` and `pageSize` https://github.com/gettyimages/gettyimages-api_nodejs/blob/master/lib/searchimageseditorial.js#L32

I've added a pull request to account for this scenario and save users much time in debugging.

**Comment by ChrisSimmons** [comment]
There are tests which _do_ test these methods. e.g.:

- https://github.com/gettyimages/gettyimages-api_nodejs/blob/master/tests/searchimagestests.js#L220
- https://github.com/gettyimages/gettyimages-api_nodejs/blob/master/tests/searchimagestests.js#L227

Of course it's possible the tests are wrong.  Still 👀 at this ...

**Comment by ChrisSimmons** [comment]
Sorry for the delay here.  New NPM version - [v5.0.0](https://www.npmjs.com/package/gettyimages-api/v/5.0.0)
