### ISSUE TITLE
Can't use safe_search query param in SearchImagesCreative and SearchVideosCreative

### ISSUE THREAD

**Issue by tali-ssky** [gettyimages/gettyimages-api_nodejs#33]
Why can't I use safe_search here? Can you please add support for this?
like a new method - `withSafeSearch(val)`

**Comment by mapitman** [comment]
Would you like to open a pull request for this feature?

**Comment by tali-ssky** [comment]
Yes, I have the code almost ready, and will open a PR today or next week

**Comment by tali-ssky** [comment]
OK, opened my PR 🙏🏻 :)

**Comment by mapitman** [comment]
While testing this change out, I found a bug in our SDK. See #38
I'll fix this issue and then publish a new version of the package including your changes as well.

**Comment by mapitman** [comment]
New release: https://github.com/gettyimages/gettyimages-api_nodejs/releases/tag/5.1.0
New version of the package has been published: https://www.npmjs.com/package/gettyimages-api/v/5.1.0
