### ISSUE TITLE
Webhook after purchasing?

### ISSUE THREAD

**Issue by vitalijalbu** [gettyimages/gettyimages-api_nodejs#45]
Hi guys, I'd need to automatically download an image after each purchase by using sdk. Is there a webhook I can use to notify my local project that he can run download proccess? Thanks.

**Comment by ChrisSimmons** [comment]
Hello,

We do not currently have functionality like that, but this is a good idea.  I'd encourage you to bring this up with your Getty sales account manager.  We'll also be talking about it internally in the Getty API team.

Thanks for the question!

**Comment by vitalijalbu** [comment]
Thanks a lot

**Comment by vitalijalbu** [comment]
![Uploading Screenshot 2023-02-10 alle 22.08.04.png…]()
