### ISSUE TITLE
Unexpected end of input error when parsing response data in webhelper.js

### ISSUE THREAD

**Issue by mysurk** [gettyimages/gettyimages-api_nodejs#9]
When doing images.execute() to get image details, there is an error when parsing the JSON data received as part of response. Here is the error. 
______________________________
undefined:0

^
SyntaxError: Unexpected end of input
  at Object.parse (native)
  at IncomingMessage.<anonymous> (/home/kaushik/NodeWorkspace/GoRaydar/indexer/node_modules/connectsdk/lib/webhelper.js:96:21)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:943:16
  at process._tickDomainCallback (node.js:463:13)
__________________________

Note: The error is observed when images.execute() calls are repeatedly sent for over 10-15 minutes.
FYI, at the client side, we are throttling number of requests at 1 API call per sec.

**Comment by mapitman** [comment]
Would you be able to send a code sample to reproduce this to [developersupport@gettyimages.com](developersupport@gettyimages.com)? A zip file would be fine.

**Comment by mapitman** [comment]
This seems to be a problem when sending thousands of requests through the SDK. We'll be looking at this bug when we next update the SDK.

**Comment by mapitman** [comment]
Fixed by pull request #11
